---
title: "treeTests_miscCodeTroubleshooting"
author: "Janet Young\n"
date: "`r Sys.Date()`\n"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggtree)
library(treeio)
library(tidytree)
library(ggplot2)
library(TDbook)
```


```{r}
# ### revert back to ggplot 3.5.2 - this is from 2025-04-09 
# ## version 4.0.0 is
# packageurl <- "http://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_3.5.2.tar.gz"
# install.packages(packageurl, repos=NULL, type="source")

### revert back to GGally 2.2.1  (2024-02-14) it says it needs 4.4.0
# # GGally_2.2.0.tar.gz
# packageurl <- "http://cran.r-project.org/src/contrib/Archive/GGally/GGally_2.2.1.tar.gz"
# install.packages(packageurl, repos=NULL, type="source")
```



# geom_tippoint and position / offset

```{r}

nwk_file <- system.file("extdata/sample.nwk", package="treeio") 
nwk_tree <- read.tree( nwk_file )


num_taxa <- length(nwk_tree$tip.label)
nwk_tree_tip_dat <- tibble( taxon=nwk_tree$tip.label,
                            fake_height= rnorm(n=num_taxa, mean=100, sd=30 ),
                            fake_phenotype= sample( c("teeth","nose","tail"), 
                                                    size=num_taxa, replace=TRUE ),
                            fake_phenotype2=sample( c("fur","scales","spikes"), 
                                                    size=num_taxa, replace=TRUE ) )

nwk_tree_with_info <- left_join(nwk_tree, nwk_tree_tip_dat, by=c("label"="taxon"))

```


add 3 works fine with default layout

```{r}
nwk_tree_with_info %>% 
    ggtree() + 
    geom_tippoint(color="blue") +
    geom_tippoint(aes(x=x+3), color="red") +
    geom_treescale()
```

Question - how does position argument to geom_tippoint work? It would be e.g. position=position_jitter()

add 3 works fine with circular layout

```{r}
nwk_tree_with_info %>% 
    ggtree(layout="circular") + 
    geom_tippoint(color="blue") +
    geom_tippoint(aes(x=x+3), color="red") 
```


add 3 works fine with fan layout

```{r}
nwk_tree_with_info %>% 
    ggtree(layout="fan") + 
    geom_tippoint(color="blue") +
    geom_tippoint(aes(x=x+3), color="red") 
```
NOT with equal angle

```{r}
nwk_tree_with_info %>% 
    ggtree(layout="equal_angle") + 
    geom_tippoint(color="blue") +
    geom_tippoint(aes(x=x+3), color="red") 
```

NOT with daylight

```{r}
nwk_tree_with_info %>% 
    ggtree(layout="daylight") + 
    geom_tippoint(color="blue") +
    geom_tippoint(aes(x=x+3), color="red") 
```


# other stuff

```{r}
#### tree_anole (phylo object) has 100 tips and 99 internal nodes
### df_svl is a data.frame, 100 rows (named like the tips of tree_anole), 1 column ("svl")
##  `tree_anole` and `df_svl` are from 'TDbook' package

svl <- as.matrix(df_svl)[,1]
fit <- phytools::fastAnc(tree_anole, svl, vars=TRUE, CI=TRUE)

#### make td - data.frame for external nodes
# 100*2 data.frame.
# nodeid() is a tidytree function that converts terminal taxon names to a numeric node ID
td <- data.frame(node = nodeid(tree_anole, names(svl)),
                 trait = svl)
#### make nd - data.frame for internal nodes:
nd <- data.frame(node = names(fit$ace), trait = fit$ace)


#### make d - combined data frame for internal and external nodes
# 199x2 - node IDs and trait value
d <- rbind(td, nd)
d$node <- as.numeric(d$node)

#### add d to the tree to make a treedata object (tree)
## tree is a 'treedata' object - contains the tree (@phylo slot) and a 199*4 tibble generated from d (with an added TRUE/FALSE column called 'isTip')
tree <- full_join(tree_anole, d, by = 'node')

p1 <- ggtree(tree, aes(color=trait), layout = 'circular', 
             ladderize = FALSE, continuous = 'colour', size=2) +
    scale_color_gradientn(colours=c("red", 'orange', 'green', 'cyan', 'blue')) +
    geom_tiplab(hjust = -.1) + 
    xlim(0, 1.2) + 
    theme(legend.position.inside = c(.05, .85)) 

p2 <- ggtree(tree, layout='circular', ladderize = FALSE, size=2.8) + 
    geom_tree(aes(color=trait), continuous = 'colour', size=2) +  
    scale_color_gradientn(colours=c("red", 'orange', 'green', 'cyan', 'blue')) +
    geom_tiplab(aes(color=trait), hjust = -.1) + 
    xlim(0, 1.2) + 
    theme(legend.position.inside = c(.05, .85)) 

plot_list(p1, p2, ncol=2, tag_levels="A")    
```





```{r ggtree example code}


### ggtree manual http://yulab-smu.top/treedata-book/chapter4.html
## treeio https://yulab-smu.top/treedata-book/chapter1.html
## tree
set.seed(2017-02-16)
tree <- rtree(50)

## beast_tree (treedata object, 76 tips, 75 internal nodes)
beast_file <- system.file("examples/MCC_FluA_H3.tree", 
                          package="ggtree")
beast_tree <- read.beast(beast_file)
# ggtree(beast_tree, mrsd="2013-01-01") + theme_tree2()


## NAG (integer vector, length 151, goes with beast_tree)
NAG_file <- system.file("examples/NAG_inHA1.txt", package="ggtree")

NAG.df <- read.table(NAG_file, sep="\t", header=FALSE, 
                     stringsAsFactors = FALSE)
NAG <- NAG.df[,2]
names(NAG) <- NAG.df[,1]

##
nwk <- system.file("extdata/RAxML","RAxML_bipartitions.H3", package='treeio')
tr <- read.tree(nwk)

ggtree(tr) + 
    geom_text2(aes(label=label, 
                   subset = !is.na(as.numeric(label)) & as.numeric(label) > 80))
```

```{r}
raxml_file <- system.file("extdata/RAxML", "RAxML_bipartitionsBranchLabels.H3", package="treeio")
raxml <- read.raxml(raxml_file)
ggtree(raxml) + geom_text(aes(label=bootstrap/100))
```



# Finished

```{r}
sessionInfo()
```

