---
title: "colorBlindness"
author: "Janet Young"
date: "`r Sys.Date()`"
output: html_document
---

see [colorBlindness package vignette](https://cran.r-project.org/web/packages/colorBlindness/vignettes/colorBlindness.html)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(colorBlindness)
library(ggplot2)
library(reshape2)
```


```{r}
mat <- matrix(1:81, nrow = 9, ncol = 9)

mat1 <- melt(t(mat[9:1, ]))
len <- length(Blue2DarkRed12Steps)-1
mat1$v2 <- cut(mat1$value,
              breaks = seq(0,ceiling(81/len)*len, 
                           length.out = len+1))
ht <- ggplot(mat1) + 
  geom_tile(aes(x=Var1, y=Var2, fill=v2)) + 
  scale_fill_manual(values=Blue2DarkRed12Steps) + 
  theme_bw()
ht
```

```{r}
# check the plot by CVD simulator
cvdPlot(ht)
```

```{r}
cvdPlot(replacePlotColor(displayColors(c("Red", "Green", "blue"))))
```

`colorBlindness::replacePlotColor` - replace the colors for plots
replace the colors of plots to meet the requirement of publication. Replacing red with magenta or green with turquoise. Replacing all the colored symbols in the legend.

