---
title: "table_display_flextable_demo"
author: "Janet Young\n"
date: "`r Sys.Date()`\n"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(kableExtra)
```

# Goal

Get conditional formatting using kable to show up in a github_document rendering.

Problem - it shows up nicely in the Rstudio interface and in the knit window that pops up, but not when we render it on the github site.

## mtcars example

```{r}
mtcars %>% 
    slice_head(n=6) %>% 
    select(am, carb, gear, mpg, drat) %>% 
    mutate(drat = cell_spec(drat, 
                            format = "html", 
                            background=ifelse(drat > 3, "red", "green"))) %>% 
    kable(# "html",
        format = "latex", 
        # booktabs = TRUE,
          caption="Example kable table", escape = FALSE) %>% 
    kable_styling(full_width = FALSE)
```

## kableExtra cookbook example

Example from here https://sharlagelfand.github.io/kableExtra-cookbook/how-to.html#

```{r, include=FALSE}
library(fivethirtyeight)
library(scales)
```

```{r}
data_noun <- comma_survey %>%
    filter(!is.na(care_data)) %>%
    select(education, care_data)


data_noun_percent <- data_noun %>%
    mutate(education = fct_explicit_na(education, na_level = "Education unknown")) %>%
    group_by(education, care_data) %>%
    summarise(n = n()) %>%
    mutate(
        prop = n / sum(n),
        percent = percent(prop)
    ) %>%
    ungroup() %>%
    select(-n)

# data_noun_percent
data_noun_percent_wide <- data_noun_percent %>%
    select(-prop) %>%
    pivot_wider(
        names_from = "care_data",
        values_from = "percent"
    )

data_noun_percent_wide
```
```{r}

data_noun_percent_wide %>%
    kable(
        col.names = c("Education", "Not at all", "Not much", "Some", "A lot"),
        align = c("lrrrr")
    ) %>%
    add_header_above(header = c(" " = 1, "How much, if at all, do you care about the debate over the use of the word 'data' as a singular or plural noun?" = 4))
```

```{r}
k <- data_noun_percent_wide %>%
    kable(
        col.names = c(
            "Education",
            names(data_noun_percent_wide)[-1]
        ),
        align = c("l", rep("r", ncol(data_noun_percent_wide) - 1))
    )

k
```
```{r}

```

```{r}

## this makes the highest proportion in each row bold

data_noun_bold_highest_prop <- data_noun_percent %>%
    group_by(education) %>%
    mutate(highest_prop = max(prop)) %>%
    mutate(percent = cell_spec(percent, format = "html", bold = prop == highest_prop))

# data_noun_bold_highest_prop

data_noun_bold_highest_prop_wide <- data_noun_bold_highest_prop %>%
    select(-prop, -highest_prop) %>%
    pivot_wider(
        names_from = "care_data",
        values_from = "percent"
    )

k_header <- c(1, ncol(data_noun_bold_highest_prop_wide) - 1)
names(k_header) <- c(" ", "How much, if at all, do you care about the debate over the use of the word 'data' as a singular or plural noun?")

data_noun_bold_highest_prop_wide %>%
    kable("html",
          col.names = c("Education", names(data_noun_bold_highest_prop_wide)[-1]),
          align = c("l", rep("r", ncol(data_noun_bold_highest_prop_wide) - 1)),
          escape = FALSE
    ) %>%
    add_header_above(header = k_header)

```
# Finished

```{r}
sessionInfo()
```


