---
title: "Untitled"
output: html_document
date: "2025-06-12"
---

# Goal

Temporary script to test things I'm trying to figure out

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(tidyverse)
# library(patchwork)
# library(ggplot2movies)

library(rtracklayer)
library(GenomicRanges)
library(here)
```

```{r}
# gr <- GRanges(seqnames="NC_001133.9",
#               ranges=IRanges(start=c(10,20,30,40)),
#               score=c(5,2,-4, 10))
# gr
```

```{r}
# y <- coverage(gr, weight = "score")
# y[which(y==0)] <- NA
# y
```

```{r}
# export(y, con=here("temp/test.bw"))
```

```{r}
# import(con=here("temp/test.bw"))
```

```{r}
# import(con="/Volumes/malik_h/user/jayoung/forOtherPeople/forGrantKing/SATAY_stuff/SATAY/240103_SATAY_Pilot_4.0/data/bedfiles/fitness_raw/A_cerulenin_fitness0cent_raw.bw")
```


```{r}
# import(con="/Volumes/malik_h/user/jayoung/forOtherPeople/forGrantKing/SATAY_stuff/SATAY/240103_SATAY_Pilot_4.0/data/bedfiles/fitness_raw/A_cerulenin_fitness0cent_raw.bw")
```


```{r}
gr <- GRanges(seqnames=rep("chr1",5),
        ranges=IRanges(start=c(5,10,15,20,25),width=1), 
        score=c(0.72869552845629478, 1.12030172459286, 1.4891584, 1.0056807, 0.9010696) )
gr
```


```{r}
cov <- coverage(gr, weight="score") 

as.numeric(cov[["chr1"]])

```

```{r}
sessionInfo()
```

