---
title: "ggmsa_demo"
author: "Janet Young\n"
date: "`r Sys.Date()`\n"
output: github_document
always_allow_html: true
---

```{r}
library(ggtree)
library(ape)
library(Biostrings)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## example from here https://github.com/YuLab-SMU/ggmsa/issues/15
protein_sequences <- system.file("extdata", "sample.fasta", package = "ggmsa")
x <- readAAStringSet(protein_sequences)
d <- as.dist(stringDist(x, method = "hamming")/width(x)[1])
tree <- bionj(d)
p <- ggtree(tree ) + geom_tiplab() #tree

data <- tidy_msa(x, start = 100,end = 350)  #msa
#tree + msa
p + geom_facet(geom = geom_msa, data = data,
               panel = 'msa', font = NULL,
               color = "Chemistry_AA")  +
    xlim_tree(1)
```

```{r}
# example from here: https://github.com/YuLab-SMU/ggmsa/issues/56
seq <- readDNAStringSet("/Volumes/malik_h/user/jayoung/git_more_repos/Rtest_and_Rnotes/Rscripts/ggmsa_tests_example_for_github.fa")
ggmsa(seq, seq_name = F,
      char_width = 0.5,
      font = NULL, border = NA, color = "Chemistry_NT") +
    geom_seqlogo(color = "Chemistry_NT")
```


```{r, fig.height=3,fig.width=11}
p <- ggmsa(seq, seq_name = F,
           char_width = 0.5,
           font = NULL, border = NA, color = "Chemistry_NT") +
    facet_msa(field=80) +
    geom_seqlogo(color = "Chemistry_NT")
ggsave(filename = "/Volumes/malik_h/user/jayoung/git_more_repos/Rtest_and_Rnotes/Rscripts/ggmsa_testPlot.pdf", p, height=3, width=11)
p
```

